--- # Installs pre-req packages
- name: Install Pre-req Packages
  apt:
    name: "{{ prereq_packages }}"
    state: latest
    update_cache: yes
  vars:
    prereq_packages:
      - pwgen 
      - whois
      - fail2ban

- name: Install WP-CLI
  get_url:
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: /usr/local/bin/wp
    mode: '0755'